
package WebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IChatServiceImplService", targetNamespace = "http://WebService/", wsdlLocation = "http://localhost:9999/ChatQueue?wsdl")
public class IChatServiceImplService
    extends Service
{

    private final static URL ICHATSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ICHATSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ICHATSERVICEIMPLSERVICE_QNAME = new QName("http://WebService/", "IChatServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ChatQueue?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ICHATSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ICHATSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IChatServiceImplService() {
        super(__getWsdlLocation(), ICHATSERVICEIMPLSERVICE_QNAME);
    }

    public IChatServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ICHATSERVICEIMPLSERVICE_QNAME, features);
    }

    public IChatServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ICHATSERVICEIMPLSERVICE_QNAME);
    }

    public IChatServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ICHATSERVICEIMPLSERVICE_QNAME, features);
    }

    public IChatServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IChatServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IChatService
     */
    @WebEndpoint(name = "IChatServiceImplPort")
    public IChatService getIChatServiceImplPort() {
        return super.getPort(new QName("http://WebService/", "IChatServiceImplPort"), IChatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IChatService
     */
    @WebEndpoint(name = "IChatServiceImplPort")
    public IChatService getIChatServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService/", "IChatServiceImplPort"), IChatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ICHATSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ICHATSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ICHATSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
