
package WebService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IChatService", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IChatService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createQueue", targetNamespace = "http://WebService/", className = "WebService.CreateQueue")
    @ResponseWrapper(localName = "createQueueResponse", targetNamespace = "http://WebService/", className = "WebService.CreateQueueResponse")
    @Action(input = "http://WebService/IChatService/createQueueRequest", output = "http://WebService/IChatService/createQueueResponse")
    public boolean createQueue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMessages", targetNamespace = "http://WebService/", className = "WebService.GetAllMessages")
    @ResponseWrapper(localName = "getAllMessagesResponse", targetNamespace = "http://WebService/", className = "WebService.GetAllMessagesResponse")
    @Action(input = "http://WebService/IChatService/getAllMessagesRequest", output = "http://WebService/IChatService/getAllMessagesResponse")
    public List<String> getAllMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "writeMessage", targetNamespace = "http://WebService/", className = "WebService.WriteMessage")
    @ResponseWrapper(localName = "writeMessageResponse", targetNamespace = "http://WebService/", className = "WebService.WriteMessageResponse")
    @Action(input = "http://WebService/IChatService/writeMessageRequest", output = "http://WebService/IChatService/writeMessageResponse")
    public String writeMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
