module Agenda{

interface ContactsNode{
     struct Contact {
        String name;
        String number;
     };
    exception unknown_user { Contact contact};
	exception user_exists { Contact contact};
	exception empty_list {};


    boolean addContact(in Contact contact) raises user_exists;
    boolean deleteContact(in Contact contact) raises unknown_user;
    boolean updateContact(in Contact oldContact, in Contact newContact) raises user_exists,unknown_user;
    sequence <Contact> getListContacts() raises empty_list;
    };
}