module Agenda{
struct Contact {
        string name;
        string number;
     };

exception unknown_user { Contact contact;};
exception user_exists { Contact contact;};
exception empty_list {};
typedef sequence<Contact> CustomerSeq;

interface ContactsNode{
    attribute CustomerSeq data;
    boolean addContact(in Contact contact) raises (user_exists);
    boolean deleteContact(in Contact contact) raises (unknown_user);
    boolean updateContact(in Contact oldContact, in Contact newContact) raises (unknown_user);
    string searchContact(in string name) raises (unknown_user);
    };
};