package Agenda.ContactsNodePackage;


/**
* Agenda/ContactsNodePackage/Contact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 1:25:48 PM BRT
*/

public final class Contact implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String number = null;

  public Contact ()
  {
  } // ctor

  public Contact (String _name, String _number)
  {
    name = _name;
    number = _number;
  } // ctor

} // class Contact
