package Agenda.ContactsNodePackage;


/**
* Agenda/ContactsNodePackage/empty_list.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 17:53:08 Horário da Guiana Francesa
*/

public final class empty_list extends org.omg.CORBA.UserException
{

  public empty_list ()
  {
    super(empty_listHelper.id());
  } // ctor


  public empty_list (String $reason)
  {
    super(empty_listHelper.id() + "  " + $reason);
  } // ctor

} // class empty_list
