package Agenda.ContactsNodePackage;

/**
* Agenda/ContactsNodePackage/unknown_userHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 17:53:08 Horário da Guiana Francesa
*/

public final class unknown_userHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.ContactsNodePackage.unknown_user value = null;

  public unknown_userHolder ()
  {
  }

  public unknown_userHolder (Agenda.ContactsNodePackage.unknown_user initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.ContactsNodePackage.unknown_userHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.ContactsNodePackage.unknown_userHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.ContactsNodePackage.unknown_userHelper.type ();
  }

}
