package Agenda.ContactsNodePackage;


/**
* Agenda/ContactsNodePackage/unknown_userHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 2:58:09 PM BRT
*/

abstract public class unknown_userHelper
{
  private static String  _id = "IDL:Agenda/ContactsNode/unknown_user:1.0";

  public static void insert (org.omg.CORBA.Any a, Agenda.ContactsNodePackage.unknown_user that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Agenda.ContactsNodePackage.unknown_user extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = Agenda.ContactsNodePackage.ContactHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "contact",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (Agenda.ContactsNodePackage.unknown_userHelper.id (), "unknown_user", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Agenda.ContactsNodePackage.unknown_user read (org.omg.CORBA.portable.InputStream istream)
  {
    Agenda.ContactsNodePackage.unknown_user value = new Agenda.ContactsNodePackage.unknown_user ();
    // read and discard the repository ID
    istream.read_string ();
    value.contact = Agenda.ContactsNodePackage.ContactHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Agenda.ContactsNodePackage.unknown_user value)
  {
    // write the repository ID
    ostream.write_string (id ());
    Agenda.ContactsNodePackage.ContactHelper.write (ostream, value.contact);
  }

}
