package Agenda.ContactsNodePackage;

/**
* Agenda/ContactsNodePackage/user_existsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 1:25:48 PM BRT
*/

public final class user_existsHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.ContactsNodePackage.user_exists value = null;

  public user_existsHolder ()
  {
  }

  public user_existsHolder (Agenda.ContactsNodePackage.user_exists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.ContactsNodePackage.user_existsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.ContactsNodePackage.user_existsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.ContactsNodePackage.user_existsHelper.type ();
  }

}
