package Agenda.ContactsNodePackage;


/**
* Agenda/ContactsNodePackage/user_exists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 1:25:48 PM BRT
*/

public final class user_exists extends org.omg.CORBA.UserException
{
  public Agenda.ContactsNodePackage.Contact contact = null;

  public user_exists ()
  {
    super(user_existsHelper.id());
  } // ctor

  public user_exists (Agenda.ContactsNodePackage.Contact _contact)
  {
    super(user_existsHelper.id());
    contact = _contact;
  } // ctor


  public user_exists (String $reason, Agenda.ContactsNodePackage.Contact _contact)
  {
    super(user_existsHelper.id() + "  " + $reason);
    contact = _contact;
  } // ctor

} // class user_exists
