package Agenda.ContactsNodePackage;


/**
* Agenda/ContactsNodePackage/user_existsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 16:59:18 Horário da Guiana Francesa
*/

abstract public class user_existsHelper
{
  private static String  _id = "IDL:Agenda/ContactsNode/user_exists:1.0";

  public static void insert (org.omg.CORBA.Any a, Agenda.ContactsNodePackage.user_exists that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Agenda.ContactsNodePackage.user_exists extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = Agenda.ContactHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "contact",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (Agenda.ContactsNodePackage.user_existsHelper.id (), "user_exists", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Agenda.ContactsNodePackage.user_exists read (org.omg.CORBA.portable.InputStream istream)
  {
    Agenda.ContactsNodePackage.user_exists value = new Agenda.ContactsNodePackage.user_exists ();
    // read and discard the repository ID
    istream.read_string ();
    value.contact = Agenda.ContactHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Agenda.ContactsNodePackage.user_exists value)
  {
    // write the repository ID
    ostream.write_string (id ());
    Agenda.ContactHelper.write (ostream, value.contact);
  }

}
