package Agenda;


/**
* Agenda/_ContactsNodeStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 17:53:08 Horário da Guiana Francesa
*/

public class _ContactsNodeStub extends org.omg.CORBA.portable.ObjectImpl implements Agenda.ContactsNode
{

  public Agenda.Contact[] data ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_data", true);
                $in = _invoke ($out);
                Agenda.Contact $result[] = Agenda.CustomerSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return data (        );
            } finally {
                _releaseReply ($in);
            }
  } // data

  public void data (Agenda.Contact[] newData)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_data", true);
                Agenda.CustomerSeqHelper.write ($out, newData);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                data (newData        );
            } finally {
                _releaseReply ($in);
            }
  } // data

  public boolean addContact (Agenda.Contact contact) throws Agenda.ContactsNodePackage.user_exists
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addContact", true);
                Agenda.ContactHelper.write ($out, contact);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Agenda/ContactsNode/user_exists:1.0"))
                    throw Agenda.ContactsNodePackage.user_existsHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addContact (contact        );
            } finally {
                _releaseReply ($in);
            }
  } // addContact

  public boolean deleteContact (Agenda.Contact contact) throws Agenda.ContactsNodePackage.unknown_user
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteContact", true);
                Agenda.ContactHelper.write ($out, contact);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Agenda/ContactsNode/unknown_user:1.0"))
                    throw Agenda.ContactsNodePackage.unknown_userHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deleteContact (contact        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteContact

  public boolean updateContact (Agenda.Contact oldContact, Agenda.Contact newContact) throws Agenda.ContactsNodePackage.unknown_user
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateContact", true);
                Agenda.ContactHelper.write ($out, oldContact);
                Agenda.ContactHelper.write ($out, newContact);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Agenda/ContactsNode/unknown_user:1.0"))
                    throw Agenda.ContactsNodePackage.unknown_userHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateContact (oldContact, newContact        );
            } finally {
                _releaseReply ($in);
            }
  } // updateContact

  public String searchContact (String name) throws Agenda.ContactsNodePackage.unknown_user
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("searchContact", true);
                $out.write_string (name);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:Agenda/ContactsNode/unknown_user:1.0"))
                    throw Agenda.ContactsNodePackage.unknown_userHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return searchContact (name        );
            } finally {
                _releaseReply ($in);
            }
  } // searchContact

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Agenda/ContactsNode:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ContactsNodeStub
