package Agenda;

/**
* Agenda/ContactsNodeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 17:53:08 Horário da Guiana Francesa
*/

public final class ContactsNodeHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.ContactsNode value = null;

  public ContactsNodeHolder ()
  {
  }

  public ContactsNodeHolder (Agenda.ContactsNode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.ContactsNodeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.ContactsNodeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.ContactsNodeHelper.type ();
  }

}
