package Agenda;


/**
* Agenda/ContactsNodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 4:04:17 PM BRT
*/

public interface ContactsNodeOperations 
{
  Agenda.Contact[] data ();
  void data (Agenda.Contact[] newData);
  boolean addContact (Agenda.Contact contact) throws Agenda.user_exists;
  boolean deleteContact (Agenda.Contact contact) throws Agenda.unknown_user;
  boolean updateContact (Agenda.Contact oldContact, Agenda.Contact newContact) throws Agenda.unknown_user;
  String searchContact (String name) throws Agenda.unknown_user;
} // interface ContactsNodeOperations
