package Agenda;


/**
* Agenda/ContactsNode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 3:22:16 PM BRT
*/

public interface ContactsNode extends ContactsNodeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ContactsNode
