package Agenda;


/**
* Agenda/ContactsNodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 17:53:08 Horário da Guiana Francesa
*/

public interface ContactsNodeOperations 
{
  Agenda.Contact[] data ();
  void data (Agenda.Contact[] newData);
  boolean addContact (Agenda.Contact contact) throws Agenda.ContactsNodePackage.user_exists;
  boolean deleteContact (Agenda.Contact contact) throws Agenda.ContactsNodePackage.unknown_user;
  boolean updateContact (Agenda.Contact oldContact, Agenda.Contact newContact) throws Agenda.ContactsNodePackage.unknown_user;
  String searchContact (String name) throws Agenda.ContactsNodePackage.unknown_user;
} // interface ContactsNodeOperations
