package Agenda;


/**
* Agenda/Contact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 16:59:18 Horário da Guiana Francesa
*/

public final class Contact implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String number = null;

  public Contact ()
  {
  } // ctor

  public Contact (String _name, String _number)
  {
    name = _name;
    number = _number;
  } // ctor

} // class Contact
