package Agenda;


/**
* Agenda/ContactsNodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 1:25:48 PM BRT
*/

public interface ContactsNodeOperations 
{
  boolean addContact (Agenda.ContactsNodePackage.Contact contact) throws Agenda.ContactsNodePackage.user_exists;
  boolean deleteContact (Agenda.ContactsNodePackage.Contact contact) throws Agenda.ContactsNodePackage.unknown_user;
  boolean updateContact (Agenda.ContactsNodePackage.Contact oldContact, Agenda.ContactsNodePackage.Contact newContact) throws Agenda.ContactsNodePackage.user_exists, Agenda.ContactsNodePackage.unknown_user;
  void getListContacts (Agenda.ContactsNodePackage.CustomerSeqHolder contacts) throws Agenda.ContactsNodePackage.empty_list;
} // interface ContactsNodeOperations
