package Agenda;


/**
* Agenda/ContactsNodePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 1:25:48 PM BRT
*/

public abstract class ContactsNodePOA extends org.omg.PortableServer.Servant
 implements Agenda.ContactsNodeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addContact", new java.lang.Integer (0));
    _methods.put ("deleteContact", new java.lang.Integer (1));
    _methods.put ("updateContact", new java.lang.Integer (2));
    _methods.put ("getListContacts", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Agenda/ContactsNode/addContact
       {
         try {
           Agenda.ContactsNodePackage.Contact contact = Agenda.ContactsNodePackage.ContactHelper.read (in);
           boolean $result = false;
           $result = this.addContact (contact);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (Agenda.ContactsNodePackage.user_exists $ex) {
           out = $rh.createExceptionReply ();
           Agenda.ContactsNodePackage.user_existsHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Agenda/ContactsNode/deleteContact
       {
         try {
           Agenda.ContactsNodePackage.Contact contact = Agenda.ContactsNodePackage.ContactHelper.read (in);
           boolean $result = false;
           $result = this.deleteContact (contact);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (Agenda.ContactsNodePackage.unknown_user $ex) {
           out = $rh.createExceptionReply ();
           Agenda.ContactsNodePackage.unknown_userHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Agenda/ContactsNode/updateContact
       {
         try {
           Agenda.ContactsNodePackage.Contact oldContact = Agenda.ContactsNodePackage.ContactHelper.read (in);
           Agenda.ContactsNodePackage.Contact newContact = Agenda.ContactsNodePackage.ContactHelper.read (in);
           boolean $result = false;
           $result = this.updateContact (oldContact, newContact);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (Agenda.ContactsNodePackage.user_exists $ex) {
           out = $rh.createExceptionReply ();
           Agenda.ContactsNodePackage.user_existsHelper.write (out, $ex);
         } catch (Agenda.ContactsNodePackage.unknown_user $ex) {
           out = $rh.createExceptionReply ();
           Agenda.ContactsNodePackage.unknown_userHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // Agenda/ContactsNode/getListContacts
       {
         try {
           Agenda.ContactsNodePackage.CustomerSeqHolder contacts = new Agenda.ContactsNodePackage.CustomerSeqHolder ();
           this.getListContacts (contacts);
           out = $rh.createReply();
           Agenda.ContactsNodePackage.CustomerSeqHelper.write (out, contacts.value);
         } catch (Agenda.ContactsNodePackage.empty_list $ex) {
           out = $rh.createExceptionReply ();
           Agenda.ContactsNodePackage.empty_listHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Agenda/ContactsNode:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ContactsNode _this() 
  {
    return ContactsNodeHelper.narrow(
    super._this_object());
  }

  public ContactsNode _this(org.omg.CORBA.ORB orb) 
  {
    return ContactsNodeHelper.narrow(
    super._this_object(orb));
  }


} // class ContactsNodePOA
