package Agenda;


/**
* Agenda/CustomerSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 3:22:16 PM BRT
*/

public final class CustomerSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.Contact value[] = null;

  public CustomerSeqHolder ()
  {
  }

  public CustomerSeqHolder (Agenda.Contact[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.CustomerSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.CustomerSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.CustomerSeqHelper.type ();
  }

}
