package Agenda;

/**
* Agenda/empty_listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 4:04:17 PM BRT
*/

public final class empty_listHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.empty_list value = null;

  public empty_listHolder ()
  {
  }

  public empty_listHolder (Agenda.empty_list initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.empty_listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.empty_listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.empty_listHelper.type ();
  }

}
