package Agenda;


/**
* Agenda/empty_list.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 3:22:16 PM BRT
*/

public final class empty_list extends org.omg.CORBA.UserException
{

  public empty_list ()
  {
    super(empty_listHelper.id());
  } // ctor


  public empty_list (String $reason)
  {
    super(empty_listHelper.id() + "  " + $reason);
  } // ctor

} // class empty_list
