package Agenda;

/**
* Agenda/unknown_userHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* Sunday, April 29, 2018 4:04:17 PM BRT
*/

public final class unknown_userHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.unknown_user value = null;

  public unknown_userHolder ()
  {
  }

  public unknown_userHolder (Agenda.unknown_user initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.unknown_userHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.unknown_userHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.unknown_userHelper.type ();
  }

}
