package Agenda;


/**
* Agenda/user_exists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 16:43:02 Horário da Guiana Francesa
*/

public final class user_exists extends org.omg.CORBA.UserException
{
  public Agenda.Contact contact = null;

  public user_exists ()
  {
    super(user_existsHelper.id());
  } // ctor

  public user_exists (Agenda.Contact _contact)
  {
    super(user_existsHelper.id());
    contact = _contact;
  } // ctor


  public user_exists (String $reason, Agenda.Contact _contact)
  {
    super(user_existsHelper.id() + "  " + $reason);
    contact = _contact;
  } // ctor

} // class user_exists
