package Agenda;

/**
* Agenda/user_existsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Agenda.idl
* domingo, 29 de abril de 2018 16:43:02 Horário da Guiana Francesa
*/

public final class user_existsHolder implements org.omg.CORBA.portable.Streamable
{
  public Agenda.user_exists value = null;

  public user_existsHolder ()
  {
  }

  public user_existsHolder (Agenda.user_exists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Agenda.user_existsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Agenda.user_existsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Agenda.user_existsHelper.type ();
  }

}
